### ISSUE TITLE
Automatically get includes path for stashes

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#100]
Currently, we have the following:
```yaml
jenkins:
  stash:
    - name: artifacts
      includes: build/libs/*.jar
      matrix_axis:
        env: GROOVY_VERSION="2.4.12"
    - name: junit
      includes: build/test-results/*.xml
      matrix_axis:
        env: GROOVY_VERSION="2.4.12"
    - name: cobertura
      includes: build/reports/cobertura/coverage.xml
      matrix_axis:
        env: GROOVY_VERSION="1.8.9"
  collect:
    artifacts: build/libs/*.jar
    cobertura: build/reports/cobertura/coverage.xml
    junit: build/test-results/*.xml
```

It's a bit of a pain.  I would much rather define the stash name without includes.  In fact, we should completely ignore user-defined includes when stashing a collect item.

```yaml
jenkins:
  pipeline_jenkinsfile: assets/Jenkinsfile
  stash:
    - name: artifacts
      matrix_axis:
        env: GROOVY_VERSION="2.4.12"
    - name: junit
      matrix_axis:
        env: GROOVY_VERSION="2.4.12"
    - name: cobertura
      matrix_axis:
        env: GROOVY_VERSION="1.8.9"
  collect:
    artifacts: build/libs/*.jar
    cobertura: build/reports/cobertura/coverage.xml
    junit: build/test-results/*.xml
```

It should be generic enough to simply prioritize the value from `collect.item` rather than the `includes` field if `collect.item` path exists.
