### ISSUE TITLE
Allow parallel on same agent and parallel limits

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#110]
```yaml
jenkins:
    parallel:
        limit: 16
        fail_fast: false
        shared_agent: true
```
If there's many builds meant to be parallel in the matrix, it might be desirable to limit concurrency.  Additionally, depending on what is being run it might be better and faster to run all the parallel steps on the same agent.
