### ISSUE TITLE
Collect HTML reports

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#115]
This is interesting because multiple HTML reports can be collected.  This means a slight re-design in report collection to not only allow maps but a list of maps as well.

Example iterating across a list of maps with an index.  Stash names will need to include the index number when there's more than one report defined for collection.
```groovy
[[a: 'hello1', b: 'world'],[a: 'hello', b: 'world']].eachWithIndex { it, i ->
    println "Index ${i}, Map ${it}"
}
```

Some YAML examples:

```yaml
jenkins:
  collect:
    html:
      path: 'html/dir1'
      reportName: 'My simple report'
```

A list of Maps defining the collection of multiple reports.

```yaml
jenkins:
  collect:
    html:
      - path: 'html/dir1'
        reportName: 'My simple report'
      - path: 'html/dir2'
        reportName: 'A second report
```
