### ISSUE TITLE
Use Jenkins Credentials inside Jervis

### ISSUE THREAD

**Issue by byjg** [samrocketman/jervis#122]
The Jervis documentation mentions "secrets". I see examples here: https://github.com/samrocketman/jervis-secrets-test

But, for use this solution I have to write in the .jervis.yml the secret text. Is there anyway to get a jenkins credentials directly from inside the Jervis?

I imagine something like this:

```yml
jenkins:
  credentials:
      - MY_SECRET_TEXT: id_jenkins_secret_text
      - MY_SECRET_USER: id_jenkins_secret_user.USERNAME
      - MY_SECRET_PASSWORD: id_jenkins_secret_user.PASSWORD
```
