### ISSUE TITLE
Optionally skip "Build Project" stage in a Jenkins pipeline

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#141]
Often, a user will override language lifecycles.  This is usually done when they want to do everything in a user-provided Jenkinsfile and not rely on the default Jervis-provided build lifecycle at all.

To optimize pipeline runtimes it does not make sense to run the `Build Project` stage when the only thing it does is install and setup the environment but **run no commands** and exit.  Jervis library should be smarter about this and optimize for it by skipping the stage when a user doesn't want to call it.

# Overriding lifecycles

Override with `true`.

```yaml
language: java
install: true
script: true
jenkins:
  pipeline_jenkinsfile: .ci/Jenkinsfile
```

Override with `/bin/true`.

```yaml
language: java
install: /bin/true
script: /bin/true
jenkins:
  pipeline_jenkinsfile: .ci/Jenkinsfile
```

Override with an empty string.

```yaml
language: java
install: ""
script: ""
jenkins:
  pipeline_jenkinsfile: .ci/Jenkinsfile
```

Override with `null`.

```yaml
language: java
install:
script:
jenkins:
  pipeline_jenkinsfile: .ci/Jenkinsfile
```

# Provide option to skip

In addition to the above hacks for optimizing skipping the `Build Project` stage, it would be nice to provide a single option for users to skip without the hack.  I think this would simplify configuration and documentation.  It is worth noting that if a user skips lifecycles, then matrix building through Jervis will not be available.  The cognitive complexity for the end user for matrix building without Jervis means it is not worth providing as an advanced Jenkinsfile feature.

Skip option.

```yaml
language: java
jenkins:
  skip_lifecycle_build: true
  pipeline_jenkinsfile: .ci/Jenkinsfile
```
