### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#62]
https://github.com/orcasnet/activerecord-recursive_tree_scopes/blob/master/.travis.yml

env is not created with a matrix value even though it is mentioned as an exclusion.

```yaml
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - .travis/activerecord-3.1.gemfile
  - .travis/activerecord-3.2.gemfile
  - .travis/activerecord-4.0.gemfile
env:
  - DB=postgresql
script:
  - rm spec/database.yml
  - mv spec/database.yml.travis spec/database.yml
  - bundle exec rspec spec
before_script:
  - psql -c 'create database activerecordrecursivetreerelationstest' -U postgres

matrix:
  exclude:
  - rvm: 1.9.2
    gemfile: .travis/activerecord-4.0.gemfile
    env: DB=postgresql
```

**Comment by samrocketman** [comment]
After some evaluation and thought I decided I like the current behavior.  Therefore, I contest that this `.travis.yml` is in a bad format and there's no point in excluding `env: DB=postgresql` when there's no matrices for it.  The actual matrix exclusion should be the following.

```yaml

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: .travis/activerecord-4.0.gemfile
```

It also did not appear to have proper indenting.
