### ISSUE TITLE
Better built-in secure field support

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#64]
Right now a lot of the work for secure field support is offloaded to the user.  I want this to be made even easier by offloading most of this work into the library.  See also #22.

**Comment by samrocketman** [comment]
Here's how it can be supported.  Based on using [`securityIO`](https://github.com/samrocketman/jervis/blob/jervis-0.3/src/main/groovy/net/gleske/jervis/tools/securityIO.groovy) and [`repository-secrets` proof of concept using openssl commands to encrypt strings](https://github.com/samrocketman/repository-secrets/blob/master/docs/proof_of_concept.md).

```yaml
jenkins:
  secrets_id: "<Jenkins RSA key identifier>"
  secrets:
    - key: MY_ENVIRONMENT_VAR
      value: <rsa encrypted string>
    - key: ANOTHER_ENVIRON_VAR
      value: <rsa encypted string>
```

Job DSL

```groovy
import jenkins.model.Jenkins

public String getFolderRSAKeyCredentials(String folder, String credentials_id) {
    def credentials
    def properties = Jenkins.getInstance().getJob(folder).getProperties()
    for(int i=0; i < properties.size(); i++) {
        if(properties.get(i).getClass().getSimpleName() == 'FolderCredentialsProperty') {
            credentials = properties.get(i)
        }
    }
    String found_credentials = ''
    if(credentials != null ) {
        credentials.getDomainCredentials().each { domain ->
            domain.getCredentials().each { credential ->
                if(credential != null && credential.getClass().getSimpleName() == 'BasicSSHUserPrivateKey') {
                    if(credential.getId() == credentials_id) {
                        found_credentials = credential.getPrivateKey()
                    }
                }
            }
        }
    }
    return found_credentials
}

println getFolderRSAKeyCredentials('folder', 'cred-id')
```
