### ISSUE TITLE
Branch exclusion support

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#8]
Jervis needs to support excluding branches in `.travis.yml` files.

```yaml
# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable
```

http://docs.travis-ci.com/user/build-configuration/#Specify-branches-to-build
