### ISSUE TITLE
Support collect item or map

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/jervis#97]
Support for both:

```yaml
jenkins:
  collect:
    artifacts: '*.jar'
```
```yaml
jenkins:
  collect:
    artifacts:
      key: value
      key2: value2
```

This will allow customizing collect items or collect items with custom settings.

There are two forms to specifying paths (`String` or `List` which gets reduced to comma separated String):

```yaml
jenkins:
  collect:
    artifacts: '*.jar,*.xml'
```
```yaml
jenkins:
  collect:
    artifacts:
      - '*.jar'
      - *.xml'
```

When defining the path to collect artifacts it should be defined in the `path` key.  For example,

```yaml
jenkins:
  collect:
    artifacts:
      path: '*.jar,*.xml'
      allow_empty_archive: true
```

Additionally, `path` should also be a `String` or `List` (which is reduced to comma separated `String`).
```yaml
jenkins:
  collect:
    artifacts:
      path: 
        - '*.jar'
        - '*.xml'
      allow_empty_archive: true
```
